---
version: '3.8'
services:
  paizadb:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: paizapass
      MYSQL_DATABASE: paizaapp
      MYSQL_USER: paizauser
      MYSQL_PASSWORD: paizaapppass
    volumes:
    - db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
    - paizadb
    ports:
    - 8092:8000
    volumes:
    - ./work:/work

volumes:
  db-data: